<a href="https://colab.research.google.com/github/ItsMohamedAyman/NumPy/blob/main/NumPy_ufunc.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. Simple Arithmetic**

## Addition

In [2]:
import numpy as np

arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2 = np.array([20, 21, 22, 23, 24, 25])

new_arr = np.add(arr1,arr2)
print(newarr)

[30 32 34 36 38 40]


## Subtraction

In [4]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.subtract(arr1, arr2)

print(newarr)

[-10  -1   8  17  26  35]


## Multiplication

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([20, 21, 22, 23, 24, 25])

newarr = np.multiply(arr1, arr2)

print(newarr)

## Division

In [5]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 10, 8, 2, 33])

newarr = np.divide(arr1, arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


## Power

In [8]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 5, 6, 8, 2, 3])

newarr = np.power(arr1, arr2)

print(newarr)

[         1000       3200000     729000000 6553600000000          2500
        216000]


## Remainder

Both the mod() and the remainder() functions return the remainder of the values in the first array corresponding to the values in the second array, and return the results in a new array.

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.mod(arr1, arr2)

print(newarr)

You get the same result when using the remainder() function:

In [ ]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.remainder(arr1, arr2)

print(newarr)

## Quotient and Mod

The divmod() function return both the quotient and the mod. The return value is two arrays, the first array contains the quotient and second array contains the mod.

In [9]:
import numpy as np

arr1 = np.array([10, 20, 30, 40, 50, 60])
arr2 = np.array([3, 7, 9, 8, 2, 33])

newarr = np.divmod(arr1, arr2)

print(newarr)

(array([ 3,  2,  3,  5, 25,  1]), array([ 1,  6,  3,  0,  0, 27]))


## Absolute Values

In [ ]:
import numpy as np

arr = np.array([-1, -2, 1, 2, 3, -4])

newarr = np.absolute(arr)

print(newarr)

# **2. Rounding Decimals**


## Truncation


Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.

In [10]:
import numpy as np

arr = np.trunc([-3.1666, 3.6667])

print(arr)

[-3.  3.]


Same example, using fix():

In [11]:
import numpy as np
arr = np.fix([-3.1666, 3.6667])
print(arr)

[-3.  3.]


## Rounding

The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

E.g. round off to 1 decimal point, 3.16666 is 3.2



In [20]:
import numpy as np

arr = np.around(3.1666, 2)

print(arr)

3.17


## Floor

The floor() function rounds off decimal to nearest lower integer.

E.g. floor of 3.166 is 3

In [21]:
import numpy as np

arr = np.floor([-3.1666, 3.6667])

print(arr)

[-4.  3.]


## Ceil

The ceil() function rounds off decimal to nearest upper integer.

E.g. ceil of 3.166 is 4

In [22]:
import numpy as np

arr = np.ceil([-3.1666, 3.6667])

print(arr)

[-3.  4.]


# **3. NumPy Logs**

## Log at Base 2

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log2(arr))

## Log at Base 10

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log10(arr))

## Natural Log, or Log at Base e

In [ ]:
import numpy as np

arr = np.arange(1, 10)

print(np.log(arr))

## Log at Any Base

In [24]:
from math import log
import numpy as np

nplog = np.frompyfunc(log, 2, 1)

print(nplog(100, 15))

1.7005483074552052
